MODEL (
    name stg.synthea__patients,
    description "Synthea patients table",
    kind VIEW,
    columns (
        patient_id varchar,
        birth_date date,
        death_date date,
        ssn varchar,
        drivers_license_number varchar,
        passport_number varchar,
        patient_prefix varchar,
        patient_first_name varchar,
        patient_last_name varchar,
        patient_suffix varchar,
        maiden_name varchar,
        marital_status varchar,
        race varchar,
        ethnicity varchar,
        patient_gender varchar,
        birthplace varchar,
        patient_address varchar,
        patient_city varchar,
        patient_state varchar,
        patient_county varchar,
        patient_zip varchar,
        patient_latitude double,
        patient_longitude double,
        healthcare_expenses double,
        healthcare_coverage double
    ),
    column_descriptions (
        patient_id = 'Unique identifier for the patient.',
        birth_date = "The patient\'s date of birth.",
        death_date = "The patient\'s date of death, if applicable.",
        ssn = 'Social Security Number.',
        drivers_license_number = "Driver\'s license number.",
        passport_number = 'Passport number.',
        patient_prefix = 'Name prefix, such as Mr., Mrs., Dr., etc.',
        patient_first_name = "Patient\'s first name.",
        patient_last_name = "Patient\'s last name.",
        patient_suffix = 'Name suffix, such as PhD, MD, JD, etc.',
        maiden_name = "Patient\'s maiden name.",
        marital_status = 'Marital Status. M is married, S is single.',
        race = "Text description of patient\'s primary race.",
        ethnicity = "Text description of patient\'s primary ethnicity.",
        patient_gender = 'Gender. M is male, F is female.',
        birthplace = 'Name of the town where the patient was born.',
        patient_address = "Patient\'s street address.",
        patient_city = "Patient\'s city.",
        patient_state = "Patient\'s state.",
        patient_county = "Patient\'s county.",
        patient_zip = "Patient\'s ZIP code.",
        patient_latitude = "Patient\'s latitude.",
        patient_longitude = "Patient\'s longitude.",
        healthcare_expenses = 'The total lifetime cost of healthcare to the patient.',
        healthcare_coverage = 'The total lifetime cost of healthcare services that were covered by Payers.'
    )
);

SELECT
    ID as patient_id,
    BIRTHDATE as birth_date,
    DEATHDATE as death_date,
    SSN as ssn,
    DRIVERS as drivers_license_number,
    PASSPORT as passport_number,
    PREFIX as patient_prefix,
    FIRST as patient_first_name,
    LAST as patient_last_name,
    SUFFIX as patient_suffix,
    MAIDEN as maiden_name,
    MARITAL as marital_status,
    RACE as race,
    ETHNICITY as ethnicity,
    GENDER as patient_gender,
    BIRTHPLACE as birthplace,
    ADDRESS as patient_address,
    CITY as patient_city,
    STATE as patient_state,
    COUNTY as patient_county,
    ZIP as patient_zip,
    LAT as patient_latitude,
    LON as patient_longitude,
    HEALTHCARE_EXPENSES as healthcare_expenses,
    HEALTHCARE_COVERAGE as healthcare_coverage
FROM synthea.patients;
