MODEL (
    name stg.synthea__payers,
    description "Synthea payers table",
    kind VIEW,
    columns (
        payer_id varchar,
        payer_name varchar,
        payer_city varchar,
        payer_state_headquartered varchar,
        payer_zip varchar,
        payer_phone varchar,
        payer_amount_covered double,
        payer_amount_uncovered double,
        payer_revenue double,
        covered_encounters int,
        uncovered_encounters int,
        covered_medications int,
        uncovered_medications int,
        covered_procedures int,
        uncovered_procedures int,
        covered_immunizations int,
        uncovered_immunizations int,
        unique_customers int,
        qols_avg double,
        payer_member_months int
    ),
    column_descriptions (
        payer_id = 'Unique identifier for the payer.',
        payer_name = 'Name of the payer.',
        payer_city = 'City of the payer.',
        payer_state_headquartered = 'State where the payer is headquartered.',
        payer_zip = 'ZIP code of the payer.',
        payer_phone = 'Phone number of the payer.',
        payer_amount_covered = 'The monetary amount paid to Organizations during the entire simulation.',
        payer_amount_uncovered = 'The monetary amount not paid to Organizations during the entire simulation, and covered out of pocket by patients.',
        payer_revenue = 'The monetary revenue of the payer during the entire simulation.',
        covered_encounters = 'The number of Encounters paid for by this Payer.',
        uncovered_encounters = 'The number of Encounters not paid for by this Payer, and paid out of pocket by patients.',
        covered_medications = 'The number of Medications paid for by this Payer.',
        uncovered_medications = 'The number of Medications not paid for by this Payer, and paid out of pocket by patients.',
        covered_procedures = 'The number of Procedures paid for by this Payer.',
        uncovered_procedures = 'The number of Procedures not paid for by this Payer, and paid out of pocket by patients.',
        covered_immunizations = 'The number of Immunizations paid for by this Payer.',
        uncovered_immunizations = 'The number of Immunizations not paid for by this Payer, and paid out of pocket by patients.',
        unique_customers = 'The number of unique patients enrolled with this Payer during the entire simulation.',
        qols_avg = 'The average Quality of Life Scores (QOLS) for all patients enrolled with this Payer during the entire simulation.',
        payer_member_months = 'The total number of months that patients were enrolled with this Payer during the simulation.'
    )
);

SELECT
    ID as payer_id,
    NAME as payer_name,
    CITY as payer_city,
    STATE_HEADQUARTERED as payer_state_headquartered,
    ZIP as payer_zip,
    PHONE as payer_phone,
    AMOUNT_COVERED as payer_amount_covered,
    AMOUNT_UNCOVERED as payer_amount_uncovered,
    REVENUE as payer_revenue,
    COVERED_ENCOUNTERS as covered_encounters,
    UNCOVERED_ENCOUNTERS as uncovered_encounters,
    COVERED_MEDICATIONS as covered_medications,
    UNCOVERED_MEDICATIONS as uncovered_medications,
    COVERED_PROCEDURES as covered_procedures,
    UNCOVERED_PROCEDURES as uncovered_procedures,
    COVERED_IMMUNIZATIONS as covered_immunizations,
    UNCOVERED_IMMUNIZATIONS as uncovered_immunizations,
    UNIQUE_CUSTOMERS as unique_customers,
    QOLS_AVG as qols_avg,
    MEMBER_MONTHS as payer_member_months
FROM synthea.payers;
