MODEL (
  name stg.synthea__patients,
  description "Synthea patients table",
  kind VIEW,
  columns (
    patient_id TEXT,
    birth_date DATE,
    death_date DATE,
    ssn TEXT,
    drivers_license_number TEXT,
    passport_number TEXT,
    patient_prefix TEXT,
    patient_first_name TEXT,
    patient_last_name TEXT,
    patient_suffix TEXT,
    maiden_name TEXT,
    marital_status TEXT,
    race TEXT,
    ethnicity TEXT,
    patient_gender TEXT,
    birthplace TEXT,
    patient_address TEXT,
    patient_city TEXT,
    patient_state TEXT,
    patient_county TEXT,
    patient_zip TEXT,
    patient_latitude DOUBLE,
    patient_longitude DOUBLE,
    healthcare_expenses DOUBLE,
    healthcare_coverage DOUBLE
  ),
  column_descriptions (patient_id = 'Unique identifier for the patient.', birth_date = "The patient\'s date of birth.", death_date = "The patient\'s date of death, if applicable.", ssn = 'Social Security Number.', drivers_license_number = "Driver\'s license number.", passport_number = 'Passport number.', patient_prefix = 'Name prefix, such as Mr., Mrs., Dr., etc.', patient_first_name = "Patient\'s first name.", patient_last_name = "Patient\'s last name.", patient_suffix = 'Name suffix, such as PhD, MD, JD, etc.', maiden_name = "Patient\'s maiden name.", marital_status = 'Marital Status. M is married, S is single.', race = "Text description of patient\'s primary race.", ethnicity = "Text description of patient\'s primary ethnicity.", patient_gender = 'Gender. M is male, F is female.', birthplace = 'Name of the town where the patient was born.', patient_address = "Patient\'s street address.", patient_city = "Patient\'s city.", patient_state = "Patient\'s state.", patient_county = "Patient\'s county.", patient_zip = "Patient\'s ZIP code.", patient_latitude = "Patient\'s latitude.", patient_longitude = "Patient\'s longitude.", healthcare_expenses = 'The total lifetime cost of healthcare to the patient.', healthcare_coverage = 'The total lifetime cost of healthcare services that were covered by Payers.')
);

SELECT
  ID AS patient_id,
  BIRTHDATE AS birth_date,
  DEATHDATE AS death_date,
  SSN AS ssn,
  DRIVERS AS drivers_license_number,
  PASSPORT AS passport_number,
  PREFIX AS patient_prefix,
  FIRST AS patient_first_name,
  LAST AS patient_last_name,
  SUFFIX AS patient_suffix,
  MAIDEN AS maiden_name,
  MARITAL AS marital_status,
  RACE AS race,
  ETHNICITY AS ethnicity,
  GENDER AS patient_gender,
  BIRTHPLACE AS birthplace,
  ADDRESS AS patient_address,
  CITY AS patient_city,
  STATE AS patient_state,
  COUNTY AS patient_county,
  ZIP AS patient_zip,
  LAT AS patient_latitude,
  LON AS patient_longitude,
  HEALTHCARE_EXPENSES AS healthcare_expenses,
  HEALTHCARE_COVERAGE AS healthcare_coverage
FROM synthea.patients