MODEL (
  name stg.synthea__payers,
  description "Synthea payers table",
  kind VIEW,
  columns (
    payer_id TEXT,
    payer_name TEXT,
    payer_city TEXT,
    payer_state_headquartered TEXT,
    payer_zip TEXT,
    payer_phone TEXT,
    payer_amount_covered DOUBLE,
    payer_amount_uncovered DOUBLE,
    payer_revenue DOUBLE,
    covered_encounters INT,
    uncovered_encounters INT,
    covered_medications INT,
    uncovered_medications INT,
    covered_procedures INT,
    uncovered_procedures INT,
    covered_immunizations INT,
    uncovered_immunizations INT,
    unique_customers INT,
    qols_avg DOUBLE,
    payer_member_months INT
  ),
  column_descriptions (
    payer_id = 'Unique identifier for the payer.',
    payer_name = 'Name of the payer.',
    payer_city = 'City of the payer.',
    payer_state_headquartered = 'State where the payer is headquartered.',
    payer_zip = 'ZIP code of the payer.',
    payer_phone = 'Phone number of the payer.',
    payer_amount_covered = 'The monetary amount paid to Organizations during the entire simulation.',
    payer_amount_uncovered = 'The monetary amount not paid to Organizations during the entire simulation, and covered out of pocket by patients.',
    payer_revenue = 'The monetary revenue of the payer during the entire simulation.',
    covered_encounters = 'The number of Encounters paid for by this Payer.',
    uncovered_encounters = 'The number of Encounters not paid for by this Payer, and paid out of pocket by patients.',
    covered_medications = 'The number of Medications paid for by this Payer.',
    uncovered_medications = 'The number of Medications not paid for by this Payer, and paid out of pocket by patients.',
    covered_procedures = 'The number of Procedures paid for by this Payer.',
    uncovered_procedures = 'The number of Procedures not paid for by this Payer, and paid out of pocket by patients.',
    covered_immunizations = 'The number of Immunizations paid for by this Payer.',
    uncovered_immunizations = 'The number of Immunizations not paid for by this Payer, and paid out of pocket by patients.',
    unique_customers = 'The number of unique patients enrolled with this Payer during the entire simulation.',
    qols_avg = 'The average Quality of Life Scores (QOLS) for all patients enrolled with this Payer during the entire simulation.',
    payer_member_months = 'The total number of months that patients were enrolled with this Payer during the simulation.'
  )
);

SELECT
  ID AS payer_id,
  NAME AS payer_name,
  CITY AS payer_city,
  STATE_HEADQUARTERED AS payer_state_headquartered,
  ZIP AS payer_zip,
  PHONE AS payer_phone,
  AMOUNT_COVERED AS payer_amount_covered,
  AMOUNT_UNCOVERED AS payer_amount_uncovered,
  REVENUE AS payer_revenue,
  COVERED_ENCOUNTERS AS covered_encounters,
  UNCOVERED_ENCOUNTERS AS uncovered_encounters,
  COVERED_MEDICATIONS AS covered_medications,
  UNCOVERED_MEDICATIONS AS uncovered_medications,
  COVERED_PROCEDURES AS covered_procedures,
  UNCOVERED_PROCEDURES AS uncovered_procedures,
  COVERED_IMMUNIZATIONS AS covered_immunizations,
  UNCOVERED_IMMUNIZATIONS AS uncovered_immunizations,
  UNIQUE_CUSTOMERS AS unique_customers,
  QOLS_AVG AS qols_avg,
  MEMBER_MONTHS AS payer_member_months
FROM synthea.payers