MODEL (
    name stg.synthea__claims,
    description "Synthea claims table",
    kind VIEW,
    columns (
        claim_id varchar,
        patient_id varchar,
        provider_id varchar,
        primary_patient_insurance_id varchar,
        secondary_patient_insurance_id varchar,
        department_id int,
        patient_department_id int,
        diagnosis_1 varchar,
        diagnosis_2 varchar,
        diagnosis_3 varchar,
        diagnosis_4 varchar,
        diagnosis_5 varchar,
        diagnosis_6 varchar,
        diagnosis_7 varchar,
        diagnosis_8 varchar,
        referring_provider_id varchar,
        encounter_id varchar,
        current_illness_date date,
        service_datetime timestamp, -- Changed from datetime to timestamp
        supervising_provider_id varchar,
        claim_status_1 varchar,
        claim_status_2 varchar,
        claim_status_patient varchar,
        outstanding_1 double, -- Changed from double precision
        outstanding_2 double,
        outstanding_patient double,
        last_billed_date_1 date,
        last_billed_date_2 date,
        last_billed_date_patient date,
        claim_type_id_1 int,
        claim_type_id_2 int
    ),
    column_descriptions (
        claim_id = 'Unique identifier for the claim.',
        patient_id = 'The patient ID.',
        provider_id = 'The provider ID.',
        primary_patient_insurance_id = 'The primary payer ID.',
        secondary_patient_insurance_id = 'The secondary payer ID.',
        department_id = 'Department ID.',
        patient_department_id = 'Patient department ID.',
        diagnosis_1 = 'Diagnosis code 1.',
        diagnosis_2 = 'Diagnosis code 2.',
        diagnosis_3 = 'Diagnosis code 3.',
        diagnosis_4 = 'Diagnosis code 4.',
        diagnosis_5 = 'Diagnosis code 5.',
        diagnosis_6 = 'Diagnosis code 6.',
        diagnosis_7 = 'Diagnosis code 7.',
        diagnosis_8 = 'Diagnosis code 8.',
        referring_provider_id = 'The referring provider ID.',
        encounter_id = 'The encounter ID.',
        current_illness_date = 'The date the patient experienced symptoms.',
        service_datetime = 'The date of the services on the claim.',
        supervising_provider_id = 'The supervising provider ID.',
        claim_status_1 = 'Status of the claim from the Primary Insurance. BILLED or CLOSED.',
        claim_status_2 = 'Status of the claim from the Secondary Insurance. BILLED or CLOSED.',
        claim_status_patient = 'Status of the claim from the Patient. BILLED or CLOSED.',
        outstanding_1 = 'Total amount of money owed by Primary Insurance.',
        outstanding_2 = 'Total amount of money owed by Secondary Insurance.',
        outstanding_patient = 'Total amount of money owed by Patient.',
        last_billed_date_1 = 'Date the claim was sent to Primary Insurance.',
        last_billed_date_2 = 'Date the claim was sent to Secondary Insurance.',
        last_billed_date_patient = 'Date the claim was sent to Patient.',
        claim_type_id_1 = 'Type of claim: 1 is professional, 2 is institutional.',
        claim_type_id_2 = 'Type of claim: 1 is professional, 2 is institutional.'
    )
);

SELECT
    ID as claim_id,
    PATIENTID as patient_id,
    PROVIDERID as provider_id,
    -- CASE WHEN PRIMARYPATIENTINSURANCEID = '0' THEN NULL ELSE PRIMARYPATIENTINSURANCEID END AS primary_patient_insurance_id, -- SQLMesh handles casting later, keep simple for staging
    PRIMARYPATIENTINSURANCEID as primary_patient_insurance_id,
    -- CASE WHEN SECONDARYPATIENTINSURANCEID = '0' THEN NULL ELSE SECONDARYPATIENTINSURANCEID END AS secondary_patient_insurance_id,
    SECONDARYPATIENTINSURANCEID as secondary_patient_insurance_id,
    DEPARTMENTID as department_id,
    PATIENTDEPARTMENTID as patient_department_id,
    DIAGNOSIS1 as diagnosis_1,
    DIAGNOSIS2 as diagnosis_2,
    DIAGNOSIS3 as diagnosis_3,
    DIAGNOSIS4 as diagnosis_4,
    DIAGNOSIS5 as diagnosis_5,
    DIAGNOSIS6 as diagnosis_6,
    DIAGNOSIS7 as diagnosis_7,
    DIAGNOSIS8 as diagnosis_8,
    REFERRINGPROVIDERID as referring_provider_id,
    APPOINTMENTID as encounter_id,
    CURRENTILLNESSDATE as current_illness_date,
    SERVICEDATE as service_datetime,
    SUPERVISINGPROVIDERID as supervising_provider_id,
    STATUS1 as claim_status_1,
    STATUS2 as claim_status_2,
    STATUSP as claim_status_patient,
    OUTSTANDING1 as outstanding_1,
    OUTSTANDING2 as outstanding_2,
    OUTSTANDINGP as outstanding_patient,
    LASTBILLEDDATE1 as last_billed_date_1,
    LASTBILLEDDATE2 as last_billed_date_2,
    LASTBILLEDDATEP as last_billed_date_patient,
    HEALTHCARECLAIMTYPEID1 as claim_type_id_1,
    HEALTHCARECLAIMTYPEID2 as claim_type_id_2
FROM synthea.claims;
