MODEL (
    name stg.synthea__claims_transactions,
    description "Synthea claim transactions table",
    kind VIEW,
    columns (
        claim_transaction_id varchar,
        claim_id varchar,
        charge_id double,
        patient_id varchar,
        transaction_type varchar,
        transaction_amount double, -- Changed from decimal
        transaction_method varchar,
        transaction_from_date date,
        transaction_to_date date,
        place_of_service varchar,
        procedure_code varchar,
        procedure_code_modifier_1 varchar,
        procedure_code_modifier_2 varchar,
        claim_diagnosis_ref_1 double,
        claim_diagnosis_ref_2 double,
        claim_diagnosis_ref_3 double,
        claim_diagnosis_ref_4 double,
        service_units double,
        department_id double,
        transaction_notes varchar,
        per_unit_amount double,
        transfer_out_id double,
        transfer_type varchar,
        payments double,
        adjustments double,
        transfers double,
        outstanding double,
        encounter_id varchar,
        claim_transaction_line_note varchar,
        patient_insurance_id varchar,
        fee_schedule_id double,
        provider_id varchar,
        supervising_provider_id varchar
    ),
    column_descriptions (
        claim_transaction_id = 'Unique identifier for the claim transaction.',
        claim_id = 'The claim ID.',
        charge_id = 'Charge ID.',
        patient_id = 'The patient ID.',
        transaction_type = 'Type of claim transaction: charge, payment, adjustment, transferin, transferout.',
        transaction_amount = 'Dollar amount for a CHARGE or TRANSFERIN.',
        transaction_method = 'Payment made by CASH, CHECK, ECHECK, COPAY, SYSTEM (adjustments without payment), or CC (credit card).',
        transaction_from_date = 'Transaction start date.',
        transaction_to_date = 'Transaction end date.',
        place_of_service = 'Foreign key to the organization.',
        procedure_code = 'Procedure code.',
        procedure_code_modifier_1 = 'Procedure code modifier 1.',
        procedure_code_modifier_2 = 'Procedure code modifier 2.',
        claim_diagnosis_ref_1 = 'Number indicating which diagnosis code from the claim applies to this transaction, 1-8 are valid options.',
        claim_diagnosis_ref_2 = 'Number indicating which diagnosis code from the claim applies to this transaction, 1-8 are valid options.',
        claim_diagnosis_ref_3 = 'Number indicating which diagnosis code from the claim applies to this transaction, 1-8 are valid options.',
        claim_diagnosis_ref_4 = 'Number indicating which diagnosis code from the claim applies to this transaction, 1-8 are valid options.',
        service_units = 'Number of units of the service.',
        department_id = 'Department ID.',
        transaction_notes = 'Transaction notes.',
        per_unit_amount = 'Cost per unit.',
        transfer_out_id = 'If the transaction is a TRANSFERIN, the Charge ID of the corresponding TRANSFEROUT row.',
        transfer_type = '1 if transferred to the primary insurance, 2 if transferred to the secondary insurance, or p if transferred to the patient.',
        payments = 'Dollar amount of a payment for a PAYMENT row.',
        adjustments = 'Dollar amount of an adjustment for an ADJUSTMENT row.',
        transfers = 'Dollar amount of a transfer for a TRANSFERIN or TRANSFEROUT row.',
        outstanding = 'Dollar amount left unpaid after this transaction was applied.',
        encounter_id = 'Foreign key to the encounter.',
        claim_transaction_line_note = 'Claim transaction line note.',
        patient_insurance_id = 'Patient insurance ID.',
        fee_schedule_id = 'Fixed to 1.',
        provider_id = 'Foreign key to the provider.',
        supervising_provider_id = 'Foreign key to the supervising provider.'
    )
);

SELECT
    ID as claim_transaction_id,
    CLAIMID as claim_id,
    CHARGEID as charge_id,
    PATIENTID as patient_id,
    TYPE as transaction_type,
    AMOUNT as transaction_amount, -- Removed cast
    METHOD as transaction_method,
    FROMDATE as transaction_from_date,
    TODATE as transaction_to_date,
    PLACEOFSERVICE as place_of_service,
    PROCEDURECODE as procedure_code,
    MODIFIER1 as procedure_code_modifier_1,
    MODIFIER2 as procedure_code_modifier_2,
    DIAGNOSISREF1 as claim_diagnosis_ref_1,
    DIAGNOSISREF2 as claim_diagnosis_ref_2,
    DIAGNOSISREF3 as claim_diagnosis_ref_3,
    DIAGNOSISREF4 as claim_diagnosis_ref_4,
    UNITS as service_units,
    DEPARTMENTID as department_id,
    NOTES as transaction_notes,
    UNITAMOUNT as per_unit_amount,
    TRANSFEROUTID as transfer_out_id,
    TRANSFERTYPE as transfer_type,
    PAYMENTS as payments,
    ADJUSTMENTS as adjustments,
    TRANSFERS as transfers,
    OUTSTANDING as outstanding,
    APPOINTMENTID as encounter_id,
    LINENOTE as claim_transaction_line_note,
    PATIENTINSURANCEID as patient_insurance_id,
    FEESCHEDULEID as fee_schedule_id,
    PROVIDERID as provider_id,
    SUPERVISINGPROVIDERID as supervising_provider_id
FROM synthea.claims_transactions;
