MODEL (
  name stg.synthea__claims,
  description "Synthea claims table",
  kind VIEW,
  columns (
    claim_id TEXT,
    patient_id TEXT,
    provider_id TEXT,
    primary_patient_insurance_id TEXT,
    secondary_patient_insurance_id TEXT,
    department_id INT,
    patient_department_id INT,
    diagnosis_1 TEXT,
    diagnosis_2 TEXT,
    diagnosis_3 TEXT,
    diagnosis_4 TEXT,
    diagnosis_5 TEXT,
    diagnosis_6 TEXT,
    diagnosis_7 TEXT,
    diagnosis_8 TEXT,
    referring_provider_id TEXT,
    encounter_id TEXT,
    current_illness_date DATE,
    service_datetime TIMESTAMP, /* Changed from datetime to timestamp */
    supervising_provider_id TEXT,
    claim_status_1 TEXT,
    claim_status_2 TEXT,
    claim_status_patient TEXT,
    outstanding_1 DOUBLE, /* Changed from double precision */
    outstanding_2 DOUBLE,
    outstanding_patient DOUBLE,
    last_billed_date_1 DATE,
    last_billed_date_2 DATE,
    last_billed_date_patient DATE,
    claim_type_id_1 INT,
    claim_type_id_2 INT
  ),
  column_descriptions (
    claim_id = 'Unique identifier for the claim.',
    patient_id = 'The patient ID.',
    provider_id = 'The provider ID.',
    primary_patient_insurance_id = 'The primary payer ID.',
    secondary_patient_insurance_id = 'The secondary payer ID.',
    department_id = 'Department ID.',
    patient_department_id = 'Patient department ID.',
    diagnosis_1 = 'Diagnosis code 1.',
    diagnosis_2 = 'Diagnosis code 2.',
    diagnosis_3 = 'Diagnosis code 3.',
    diagnosis_4 = 'Diagnosis code 4.',
    diagnosis_5 = 'Diagnosis code 5.',
    diagnosis_6 = 'Diagnosis code 6.',
    diagnosis_7 = 'Diagnosis code 7.',
    diagnosis_8 = 'Diagnosis code 8.',
    referring_provider_id = 'The referring provider ID.',
    encounter_id = 'The encounter ID.',
    current_illness_date = 'The date the patient experienced symptoms.',
    service_datetime = 'The date of the services on the claim.',
    supervising_provider_id = 'The supervising provider ID.',
    claim_status_1 = 'Status of the claim from the Primary Insurance. BILLED or CLOSED.',
    claim_status_2 = 'Status of the claim from the Secondary Insurance. BILLED or CLOSED.',
    claim_status_patient = 'Status of the claim from the Patient. BILLED or CLOSED.',
    outstanding_1 = 'Total amount of money owed by Primary Insurance.',
    outstanding_2 = 'Total amount of money owed by Secondary Insurance.',
    outstanding_patient = 'Total amount of money owed by Patient.',
    last_billed_date_1 = 'Date the claim was sent to Primary Insurance.',
    last_billed_date_2 = 'Date the claim was sent to Secondary Insurance.',
    last_billed_date_patient = 'Date the claim was sent to Patient.',
    claim_type_id_1 = 'Type of claim: 1 is professional, 2 is institutional.',
    claim_type_id_2 = 'Type of claim: 1 is professional, 2 is institutional.'
  )
);

SELECT
  ID AS claim_id,
  PATIENTID AS patient_id,
  PROVIDERID AS provider_id,
  PRIMARYPATIENTINSURANCEID AS primary_patient_insurance_id, /* CASE WHEN PRIMARYPATIENTINSURANCEID = '0' THEN NULL ELSE PRIMARYPATIENTINSURANCEID END AS primary_patient_insurance_id, -- SQLMesh handles casting later, keep simple for staging */
  SECONDARYPATIENTINSURANCEID AS secondary_patient_insurance_id, /* CASE WHEN SECONDARYPATIENTINSURANCEID = '0' THEN NULL ELSE SECONDARYPATIENTINSURANCEID END AS secondary_patient_insurance_id, */
  DEPARTMENTID AS department_id,
  PATIENTDEPARTMENTID AS patient_department_id,
  DIAGNOSIS1 AS diagnosis_1,
  DIAGNOSIS2 AS diagnosis_2,
  DIAGNOSIS3 AS diagnosis_3,
  DIAGNOSIS4 AS diagnosis_4,
  DIAGNOSIS5 AS diagnosis_5,
  DIAGNOSIS6 AS diagnosis_6,
  DIAGNOSIS7 AS diagnosis_7,
  DIAGNOSIS8 AS diagnosis_8,
  REFERRINGPROVIDERID AS referring_provider_id,
  APPOINTMENTID AS encounter_id,
  CURRENTILLNESSDATE AS current_illness_date,
  SERVICEDATE AS service_datetime,
  SUPERVISINGPROVIDERID AS supervising_provider_id,
  STATUS1 AS claim_status_1,
  STATUS2 AS claim_status_2,
  STATUSP AS claim_status_patient,
  OUTSTANDING1 AS outstanding_1,
  OUTSTANDING2 AS outstanding_2,
  OUTSTANDINGP AS outstanding_patient,
  LASTBILLEDDATE1 AS last_billed_date_1,
  LASTBILLEDDATE2 AS last_billed_date_2,
  LASTBILLEDDATEP AS last_billed_date_patient,
  HEALTHCARECLAIMTYPEID1 AS claim_type_id_1,
  HEALTHCARECLAIMTYPEID2 AS claim_type_id_2
FROM synthea.claims