MODEL (
  name omop.dose_era,
  kind FULL,
  description "A Dose Era is defined as a span of time when the Person is assumed to be exposed to a constant dose of a specific active ingredient.",
  columns (
    dose_era_id BIGINT,
    person_id BIGINT,
    drug_concept_id INT,
    unit_concept_id INT,
    dose_value REAL,
    dose_era_start_date DATE,
    dose_era_end_date DATE
  ),
  column_descriptions (dose_era_id = 'A unique identifier for each Dose Era.', person_id = 'A foreign key identifier to the Person.', drug_concept_id = 'A foreign key identifier to the Drug Concept representing the specific drug ingredient.', unit_concept_id = 'A foreign key identifier to the Concept representing the unit of the drug ingredient dosage.', dose_value = 'The numeric value of the dosage of the drug ingredient.', dose_era_start_date = 'The start date of the Dose Era.', dose_era_end_date = 'The end date of the Dose Era.')
);

/* Note: This model is typically generated by OMOP-specific tools or derived datasets, */ /* not directly from raw Synthea data in this basic ETL. */ /* Creating an empty table structure for compatibility. */
SELECT
  NULL::BIGINT AS dose_era_id,
  NULL::BIGINT AS person_id,
  NULL::INT AS drug_concept_id,
  NULL::INT AS unit_concept_id,
  NULL::REAL AS dose_value,
  NULL::DATE AS dose_era_start_date,
  NULL::DATE AS dose_era_end_date
WHERE
  1 = 0