MODEL (
  name omop.drug_exposure,
  kind FULL,
  description "This table captures records about the exposure to a Drug ingested or otherwise introduced into the body.",
  columns (
    drug_exposure_id BIGINT,
    person_id BIGINT,
    drug_concept_id INT,
    drug_exposure_start_date DATE,
    drug_exposure_start_datetime TIMESTAMP,
    drug_exposure_end_date DATE,
    drug_exposure_end_datetime TIMESTAMP,
    verbatim_end_date DATE,
    drug_type_concept_id INT,
    stop_reason TEXT,
    refills INT,
    quantity REAL,
    days_supply INT,
    sig TEXT,
    route_concept_id INT,
    lot_number TEXT,
    provider_id BIGINT,
    visit_occurrence_id BIGINT,
    visit_detail_id BIGINT,
    drug_source_value TEXT,
    drug_source_concept_id INT,
    route_source_value TEXT,
    dose_unit_source_value TEXT
  ),
  column_descriptions (
    drug_exposure_id = 'A unique identifier for each drug exposure event.',
    person_id = 'A foreign key identifier to the Person associated with the drug exposure.',
    drug_concept_id = 'A foreign key identifier to the Standard Concept for the drug.',
    drug_exposure_start_date = 'The date when the drug exposure first occurred.',
    drug_exposure_start_datetime = 'The date and time when the drug exposure first occurred.',
    drug_exposure_end_date = 'The date when the drug exposure ended.',
    drug_exposure_end_datetime = 'The date and time when the drug exposure ended.',
    verbatim_end_date = 'The verbatim end date from the source data.',
    drug_type_concept_id = 'A foreign key identifier to the Concept defining the type of drug exposure.',
    stop_reason = 'The reason the drug exposure was stopped.',
    refills = 'The number of refills ordered.',
    quantity = 'The quantity of the drug supplied or administered.',
    days_supply = 'The number of days the drug supply is expected to last.',
    sig = 'The verbatim instructions for the drug administration.',
    route_concept_id = 'A foreign key identifier to the Concept defining the route of administration.',
    lot_number = 'The lot number of the drug product.',
    provider_id = 'A foreign key identifier to the Provider associated with the drug exposure.',
    visit_occurrence_id = 'A foreign key identifier to the Visit Occurrence during which the drug exposure occurred.',
    visit_detail_id = 'A foreign key identifier to the Visit Detail during which the drug exposure occurred.',
    drug_source_value = 'The source code for the drug as it appears in the source data.',
    drug_source_concept_id = 'A foreign key identifier to a Drug Concept that refers to the code used in the source.',
    route_source_value = 'The source value for the route of administration.',
    dose_unit_source_value = 'The source value for the dose unit.'
  ),
  audits (
    person_completeness_drug_exposure,
    drug_exposure_drug_concept_id_is_required,
    drug_exposure_drug_concept_id_is_foreign_key,
    drug_exposure_drug_concept_id_fk_domain,
    drug_exposure_drug_concept_id_is_standard_valid_concept,
    drug_exposure_drug_concept_id_standard_concept_record_completeness,
    drug_exposure_drug_exposure_end_date_is_required,
    drug_exposure_drug_exposure_end_date_after_birth,
    drug_exposure_drug_exposure_end_datetime_after_birth,
    drug_exposure_drug_exposure_id_is_required,
    drug_exposure_drug_exposure_id_is_primary_key,
    drug_exposure_drug_exposure_start_date_is_required,
    drug_exposure_drug_exposure_start_date_start_before_end,
    drug_exposure_drug_exposure_start_date_after_birth,
    drug_exposure_drug_exposure_start_datetime_start_before_end,
    drug_exposure_drug_exposure_start_datetime_after_birth,
    drug_exposure_drug_source_concept_id_is_foreign_key,
    drug_exposure_drug_type_concept_id_is_required,
    drug_exposure_drug_type_concept_id_is_foreign_key,
    drug_exposure_drug_type_concept_id_fk_domain,
    drug_exposure_drug_type_concept_id_is_standard_valid_concept,
    drug_exposure_drug_type_concept_id_standard_concept_record_completeness,
    drug_exposure_person_id_is_required,
    drug_exposure_person_id_is_foreign_key,
    drug_exposure_provider_id_is_foreign_key,
    drug_exposure_route_concept_id_is_foreign_key,
    drug_exposure_route_concept_id_fk_domain,
    drug_exposure_route_concept_id_is_standard_valid_concept,
    drug_exposure_route_concept_id_standard_concept_record_completeness,
    drug_exposure_verbatim_end_date_after_birth,
    drug_exposure_visit_detail_id_is_foreign_key,
    drug_exposure_visit_occurrence_id_is_foreign_key
  )
);

SELECT
  drug_exposure_id::BIGINT,
  person_id::BIGINT,
  drug_concept_id::INT,
  drug_exposure_start_date::DATE,
  drug_exposure_start_datetime::TIMESTAMP,
  drug_exposure_end_date::DATE,
  drug_exposure_end_datetime::TIMESTAMP,
  verbatim_end_date::DATE,
  drug_type_concept_id::INT,
  stop_reason::TEXT,
  refills::INT,
  quantity::REAL,
  days_supply::INT,
  sig::TEXT,
  route_concept_id::INT,
  lot_number::TEXT,
  provider_id::BIGINT,
  visit_occurrence_id::BIGINT,
  visit_detail_id::BIGINT,
  drug_source_value::TEXT,
  drug_source_concept_id::INT,
  route_source_value::TEXT,
  dose_unit_source_value::TEXT
FROM int.drug_exposure