MODEL (
  name omop.episode,
  kind FULL,
  description "The EPISODE table aggregates lower-level clinical events into a higher-level abstraction representing clinically and analytically relevant disease phases, outcomes and treatments.",
  columns (
    episode_id BIGINT,
    person_id BIGINT,
    episode_concept_id INT,
    episode_start_date DATE,
    episode_start_datetime TIMESTAMP,
    episode_end_date DATE,
    episode_end_datetime TIMESTAMP,
    episode_parent_id BIGINT,
    episode_number INT,
    episode_object_concept_id INT,
    episode_type_concept_id INT,
    episode_source_value TEXT,
    episode_source_concept_id INT
  ),
  column_descriptions (episode_id = 'A unique identifier for each Episode.', person_id = 'A foreign key identifier to the Person for whom the episode is recorded.', episode_concept_id = 'A foreign key identifier to the Standard Concept representing the Episode.', episode_start_date = 'The start date of the Episode.', episode_start_datetime = 'The start date and time of the Episode.', episode_end_date = 'The end date of the Episode.', episode_end_datetime = 'The end date and time of the Episode.', episode_parent_id = 'A foreign key identifier to the parent Episode.', episode_number = 'The sequential number of the Episode for the Person.', episode_object_concept_id = 'A foreign key identifier to the Concept representing the object (e.g., Condition) associated with the Episode.', episode_type_concept_id = 'A foreign key identifier to the Concept defining the type of Episode.', episode_source_value = 'The source value for the Episode.', episode_source_concept_id = 'A foreign key identifier to a Concept that refers to the source value.')
);

/* Note: This model is typically generated by OMOP-specific tools or derived datasets, */ /* not directly from raw Synthea data in this basic ETL. */ /* Creating an empty table structure for compatibility. */
SELECT
  NULL::BIGINT AS episode_id,
  NULL::BIGINT AS person_id,
  NULL::INT AS episode_concept_id,
  NULL::DATE AS episode_start_date,
  NULL::TIMESTAMP AS episode_start_datetime,
  NULL::DATE AS episode_end_date,
  NULL::TIMESTAMP AS episode_end_datetime,
  NULL::BIGINT AS episode_parent_id,
  NULL::INT AS episode_number,
  NULL::INT AS episode_object_concept_id,
  NULL::INT AS episode_type_concept_id,
  NULL::TEXT AS episode_source_value,
  NULL::INT AS episode_source_concept_id
WHERE
  1 = 0