MODEL (
  name omop.fact_relationship,
  kind FULL,
  description "The FACT_RELATIONSHIP table contains records about the relationships between facts stored as records in any table of the CDM.",
  columns (
    domain_concept_id_1 INT,
    fact_id_1 BIGINT,
    domain_concept_id_2 INT,
    fact_id_2 BIGINT,
    relationship_concept_id INT
  ),
  column_descriptions (
    domain_concept_id_1 = 'A foreign key identifier to the Concept defining the domain of the first fact.',
    fact_id_1 = 'The primary key identifier of the first fact.',
    domain_concept_id_2 = 'A foreign key identifier to the Concept defining the domain of the second fact.',
    fact_id_2 = 'The primary key identifier of the second fact.',
    relationship_concept_id = 'A foreign key identifier to the Concept defining the relationship between the facts.'
  )
);

-- Note: This model is typically generated by OMOP-specific tools or derived datasets,
-- not directly from raw Synthea data in this basic ETL.
-- Creating an empty table structure for compatibility.
SELECT
    CAST(NULL AS INT) AS domain_concept_id_1,
    CAST(NULL AS BIGINT) AS fact_id_1,
    CAST(NULL AS INT) AS domain_concept_id_2,
    CAST(NULL AS BIGINT) AS fact_id_2,
    CAST(NULL AS INT) AS relationship_concept_id
WHERE 1 = 0