MODEL (
    name omop.note,
    description 'The NOTE table captures unstructured information that was recorded by a provider about a patient in free text notes.',
    kind FULL,
    columns (
        note_id BIGINT,
        person_id BIGINT,
        note_date DATE,
        note_datetime TIMESTAMP,
        note_type_concept_id INT,
        note_class_concept_id INT,
        note_title VARCHAR,
        note_text VARCHAR,
        encoding_concept_id INT,
        language_concept_id INT,
        provider_id BIGINT,
        visit_occurrence_id BIGINT,
        visit_detail_id BIGINT,
        note_source_value VARCHAR,
        note_event_id BIGINT,
        note_event_field_concept_id INT
    ),
    column_descriptions (
        note_id = 'A unique identifier for each note.',
        person_id = 'A foreign key identifier to the Person about whom the note was recorded.',
        note_date = 'The date the note was recorded.',
        note_datetime = 'The date and time the note was recorded.',
        note_type_concept_id = 'A foreign key identifier to the Concept defining the type of note.',
        note_class_concept_id = 'A foreign key identifier to the Concept defining the class of the note.',
        note_title = 'The title of the note.',
        note_text = 'The content of the note.',
        encoding_concept_id = 'A foreign key identifier to the Concept defining the encoding of the note text.',
        language_concept_id = 'A foreign key identifier to the Concept defining the language of the note.',
        provider_id = 'A foreign key identifier to the Provider who recorded the note.',
        visit_occurrence_id = 'A foreign key identifier to the Visit Occurrence during which the note was recorded.',
        visit_detail_id = 'A foreign key identifier to the Visit Detail during which the note was recorded.',
        note_source_value = 'The source identifier for the note.',
        note_event_id = 'A foreign key to the clinical event table to which the note refers.',
        note_event_field_concept_id = 'A foreign key to the CONCEPT table indicating the domain of the clinical event table.'
    )
);

SELECT
    CAST(NULL AS BIGINT) AS note_id,
    CAST(NULL AS BIGINT) AS person_id,
    CAST(NULL AS DATE) AS note_date,
    CAST(NULL AS TIMESTAMP) AS note_datetime,
    CAST(NULL AS INT) AS note_type_concept_id,
    CAST(NULL AS INT) AS note_class_concept_id,
    CAST(NULL AS VARCHAR) AS note_title,
    CAST(NULL AS VARCHAR) AS note_text,
    CAST(NULL AS INT) AS encoding_concept_id,
    CAST(NULL AS INT) AS language_concept_id,
    CAST(NULL AS BIGINT) AS provider_id,
    CAST(NULL AS BIGINT) AS visit_occurrence_id,
    CAST(NULL AS BIGINT) AS visit_detail_id,
    CAST(NULL AS VARCHAR) AS note_source_value,
    CAST(NULL AS BIGINT) AS note_event_id,
    CAST(NULL AS INT) AS note_event_field_concept_id
WHERE 1 = 0;