MODEL (
  name omop.person,
  kind FULL,
  cron '@daily',
  description 'This table serves as the central identity management for all Persons in the database. It contains records that uniquely identify each person or patient, and some demographic information.',
  columns (
    person_id INT,
    gender_concept_id INT,
    year_of_birth INT,
    month_of_birth INT,
    day_of_birth INT,
    birth_datetime TIMESTAMP,
    race_concept_id INT,
    ethnicity_concept_id INT,
    location_id INT,
    provider_id INT,
    care_site_id INT,
    person_source_value TEXT,
    gender_source_value TEXT,
    gender_source_concept_id INT,
    race_source_value TEXT,
    race_source_concept_id INT,
    ethnicity_source_value TEXT,
    ethnicity_source_concept_id INT
  ),
  column_descriptions (person_id = 'A unique identifier for each person.', gender_concept_id = 'The gender of the person.', year_of_birth = 'The year of birth of the person.', month_of_birth = 'The month of birth of the person.', day_of_birth = 'The day of birth of the person.', birth_datetime = 'The date and time of birth of the person.', race_concept_id = 'The race of the person.', ethnicity_concept_id = 'The ethnicity of the person.', location_id = 'A foreign key to the location record.', provider_id = 'A foreign key to the provider record.', care_site_id = 'A foreign key to the care site record.', person_source_value = 'The source representation of the person identifier.', gender_source_value = 'The source representation of the gender.', gender_source_concept_id = 'The source concept for gender.', race_source_value = 'The source representation of the race.', race_source_concept_id = 'The source concept for race.', ethnicity_source_value = 'The source representation of the ethnicity.', ethnicity_source_concept_id = 'The source concept for ethnicity.'),
  grain (person_id),
  audits (unique_values(columns := (person_id)))
);

SELECT
  person_id,
  gender_concept_id,
  year_of_birth,
  month_of_birth,
  day_of_birth,
  birth_datetime,
  race_concept_id,
  ethnicity_concept_id,
  location_id,
  provider_id,
  care_site_id,
  person_source_value,
  gender_source_value,
  gender_source_concept_id,
  race_source_value,
  race_source_concept_id,
  ethnicity_source_value,
  ethnicity_source_concept_id
FROM int.person