MODEL (
  name omop.procedure_occurrence,
  kind FULL,
  description "Contains records of activities or processes ordered by, or carried out by, a healthcare provider on the patient with a diagnostic or therapeutic purpose.",
  column_descriptions (
    procedure_occurrence_id = "A unique identifier for each procedure occurrence.",
    person_id = "A foreign key identifier to the Person on whom the procedure was performed.",
    procedure_concept_id = "A foreign key identifier to the Standard Concept for the procedure.",
    procedure_date = "The date when the procedure occurred.",
    procedure_datetime = "The date and time when the procedure occurred.",
    procedure_end_date = "The date when the procedure ended.",
    procedure_end_datetime = "The date and time when the procedure ended.",
    procedure_type_concept_id = "A foreign key identifier to the Concept defining the type of procedure occurrence.",
    modifier_concept_id = "A foreign key identifier to the Concept providing additional information about the procedure.",
    quantity = "The number of procedures performed.",
    provider_id = "A foreign key identifier to the Provider who performed the procedure.",
    visit_occurrence_id = "A foreign key identifier to the Visit Occurrence during which the procedure occurred.",
    visit_detail_id = "A foreign key identifier to the Visit Detail during which the procedure occurred.",
    procedure_source_value = "The source code for the procedure as it appears in the source data.",
    procedure_source_concept_id = "A foreign key identifier to a Procedure Concept that refers to the code used in the source.",
    modifier_source_value = "The source value for the procedure modifier."
  ),
  audits (
    person_completeness_procedure_occurrence,
    procedure_occurrence_modifier_concept_id_is_foreign_key,
    procedure_occurrence_modifier_concept_id_is_standard_valid_concept,
    procedure_occurrence_modifier_concept_id_standard_concept_record_completeness,
    procedure_occurrence_person_id_is_required,
    procedure_occurrence_person_id_is_foreign_key,
    procedure_occurrence_procedure_concept_id_is_required,
    procedure_occurrence_procedure_concept_id_is_foreign_key,
    procedure_occurrence_procedure_concept_id_fk_domain,
    procedure_occurrence_procedure_concept_id_is_standard_valid_concept,
    procedure_occurrence_procedure_concept_id_standard_concept_record_completeness,
    procedure_occurrence_procedure_date_is_required,
    procedure_occurrence_procedure_date_start_before_end,
    procedure_occurrence_procedure_date_after_birth,
    procedure_occurrence_procedure_datetime_start_before_end,
    procedure_occurrence_procedure_datetime_after_birth,
    procedure_occurrence_procedure_end_date_after_birth,
    procedure_occurrence_procedure_end_datetime_after_birth,
    procedure_occurrence_procedure_occurrence_id_is_required,
    procedure_occurrence_procedure_occurrence_id_is_primary_key,
    procedure_occurrence_procedure_source_concept_id_is_foreign_key,
    procedure_occurrence_procedure_type_concept_id_is_required,
    procedure_occurrence_procedure_type_concept_id_is_foreign_key,
    procedure_occurrence_procedure_type_concept_id_fk_domain,
    procedure_occurrence_procedure_type_concept_id_is_standard_valid_concept,
    procedure_occurrence_procedure_type_concept_id_standard_concept_record_completeness,
    procedure_occurrence_provider_id_is_foreign_key,
    procedure_occurrence_visit_detail_id_is_foreign_key,
    procedure_occurrence_visit_occurrence_id_is_foreign_key,
    procedure_occurrence_2003947_gender,
    procedure_occurrence_2003966_gender,
    procedure_occurrence_2003983_gender,
    procedure_occurrence_2004031_gender,
    procedure_occurrence_2004063_gender,
    procedure_occurrence_2004070_gender,
    procedure_occurrence_2004090_gender,
    procedure_occurrence_2004164_gender,
    procedure_occurrence_2004263_gender,
    procedure_occurrence_2004329_gender,
    procedure_occurrence_2004342_gender,
    procedure_occurrence_2004443_gender,
    procedure_occurrence_2004627_gender,
    procedure_occurrence_2109825_gender,
    procedure_occurrence_2109833_gender,
    procedure_occurrence_2109900_gender,
    procedure_occurrence_2109902_gender,
    procedure_occurrence_2109905_gender,
    procedure_occurrence_2109906_gender,
    procedure_occurrence_2109916_gender,
    procedure_occurrence_2109968_gender,
    procedure_occurrence_2109973_gender,
    procedure_occurrence_2109981_gender,
    procedure_occurrence_2110004_gender,
    procedure_occurrence_2110011_gender,
    procedure_occurrence_2110026_gender,
    procedure_occurrence_2110039_gender,
    procedure_occurrence_2110044_gender,
    procedure_occurrence_2110078_gender,
    procedure_occurrence_2110116_gender,
    procedure_occurrence_2110142_gender,
    procedure_occurrence_2110144_gender,
    procedure_occurrence_2110169_gender,
    procedure_occurrence_2110175_gender,
    procedure_occurrence_2110194_gender,
    procedure_occurrence_2110195_gender,
    procedure_occurrence_2110203_gender,
    procedure_occurrence_2110222_gender,
    procedure_occurrence_2110227_gender,
    procedure_occurrence_2110230_gender,
    procedure_occurrence_2110307_gender,
    procedure_occurrence_2110315_gender,
    procedure_occurrence_2110316_gender,
    procedure_occurrence_2110317_gender,
    procedure_occurrence_2110326_gender,
    procedure_occurrence_2211747_gender,
    procedure_occurrence_2211749_gender,
    procedure_occurrence_2211751_gender,
    procedure_occurrence_2211753_gender,
    procedure_occurrence_2211755_gender,
    procedure_occurrence_2211756_gender,
    procedure_occurrence_2211757_gender,
    procedure_occurrence_2211765_gender,
    procedure_occurrence_2211769_gender,
    procedure_occurrence_2617204_gender,
    procedure_occurrence_2721063_gender,
    procedure_occurrence_2721064_gender,
    procedure_occurrence_2780478_gender,
    procedure_occurrence_2780523_gender,
    procedure_occurrence_4021531_gender,
    procedure_occurrence_4032622_gender,
    procedure_occurrence_4038747_gender,
    procedure_occurrence_4052532_gender,
    procedure_occurrence_4058792_gender,
    procedure_occurrence_4073700_gender,
    procedure_occurrence_4083772_gender,
    procedure_occurrence_4096783_gender,
    procedure_occurrence_4127886_gender,
    procedure_occurrence_4138738_gender,
    procedure_occurrence_4141940_gender,
    procedure_occurrence_4146777_gender,
    procedure_occurrence_4161944_gender,
    procedure_occurrence_4181912_gender,
    procedure_occurrence_4234536_gender,
    procedure_occurrence_4238715_gender,
    procedure_occurrence_4243919_gender,
    procedure_occurrence_4275113_gender,
    procedure_occurrence_4294805_gender,
    procedure_occurrence_4306780_gender,
    procedure_occurrence_4310552_gender,
    procedure_occurrence_4321575_gender,
    procedure_occurrence_4330583_gender,
    procedure_occurrence_4041261_gender_desc,
    procedure_occurrence_4250917_gender_desc,
    procedure_occurrence_4077750_gender_desc,
    procedure_occurrence_4043199_gender_desc,
    procedure_occurrence_4040577_gender_desc
  )
);

SELECT
  po.procedure_occurrence_id,
  po.person_id,
  po.procedure_concept_id,
  po.procedure_date,
  po.procedure_datetime,
  po.procedure_end_date,
  po.procedure_end_datetime,
  po.procedure_type_concept_id,
  po.modifier_concept_id,
  po.quantity,
  vd.provider_id,
  vd.visit_occurrence_id,
  vd.visit_detail_id,
  po.procedure_source_value,
  po.procedure_source_concept_id,
  po.modifier_source_value
FROM int.procedure_occurrence AS po
LEFT JOIN int.visit_detail AS vd
  ON po.encounter_id = vd.encounter_id