MODEL (
  name omop.specimen,
  kind FULL,
  description 'OMOP Specimen table - Currently empty as per source dbt model.',
  columns (
    specimen_id BIGINT,
    person_id BIGINT,
    specimen_concept_id INT,
    specimen_type_concept_id INT,
    specimen_date DATE,
    specimen_datetime TIMESTAMP,
    quantity DECIMAL(18, 3),
    unit_concept_id INT,
    anatomic_site_concept_id INT,
    disease_status_concept_id INT,
    specimen_source_id TEXT,
    specimen_source_value TEXT,
    unit_source_value TEXT,
    anatomic_site_source_value TEXT,
    disease_status_source_value TEXT
  ),
  column_descriptions (
    specimen_id = 'A unique identifier for each specimen.',
    person_id = 'A foreign key identifier to the Person associated with the specimen.',
    specimen_concept_id = 'A foreign key to the standard Concept identifier in the Standardized Vocabularies for the specimen.',
    specimen_type_concept_id = 'A foreign key to the standard Concept identifier in the Standardized Vocabularies defining the type of specimen.',
    specimen_date = 'The date on which the specimen was collected.',
    specimen_datetime = 'The date and time on which the specimen was collected.',
    quantity = 'The quantity or amount of the specimen collected.',
    unit_concept_id = 'A foreign key to the standard Concept identifier in the Standardized Vocabularies for the unit of the specimen quantity.',
    anatomic_site_concept_id = 'A foreign key to the standard Concept identifier in the Standardized Vocabularies for the anatomic site from which the specimen was collected.',
    disease_status_concept_id = 'A foreign key to the standard Concept identifier in the Standardized Vocabularies for the disease status associated with the specimen.',
    specimen_source_id = 'An identifier for the source specimen.',
    specimen_source_value = 'The source code for the specimen as it appears in the source data.',
    unit_source_value = 'The source code for the unit of the specimen quantity.',
    anatomic_site_source_value = 'The source code for the anatomic site from which the specimen was collected.',
    disease_status_source_value = 'The source code for the disease status associated with the specimen.'
  ),
  audits (
    person_completeness_specimen,
    specimen_anatomic_site_concept_id_is_foreign_key,
    specimen_anatomic_site_concept_id_is_standard_valid_concept,
    specimen_disease_status_concept_id_is_foreign_key,
    specimen_disease_status_concept_id_is_standard_valid_concept,
    specimen_person_id_is_required,
    specimen_person_id_is_foreign_key,
    specimen_specimen_concept_id_is_required,
    specimen_specimen_concept_id_is_foreign_key,
    specimen_specimen_concept_id_is_standard_valid_concept,
    specimen_specimen_concept_id_standard_concept_record_completeness,
    specimen_specimen_date_is_required,
    specimen_specimen_date_after_birth,
    specimen_specimen_datetime_after_birth,
    specimen_specimen_id_is_required,
    specimen_specimen_id_is_primary_key,
    specimen_specimen_type_concept_id_is_required,
    specimen_specimen_type_concept_id_is_foreign_key,
    specimen_specimen_type_concept_id_fk_domain,
    specimen_specimen_type_concept_id_is_standard_valid_concept,
    specimen_specimen_type_concept_id_standard_concept_record_completeness,
    specimen_unit_concept_id_is_foreign_key,
    specimen_unit_concept_id_is_standard_valid_concept,
    specimen_unit_concept_id_standard_concept_record_completeness
  ),
  dialect 'duckdb'
);

SELECT
  NULL::BIGINT AS specimen_id,
  NULL::BIGINT AS person_id,
  NULL::INT AS specimen_concept_id,
  NULL::INT AS specimen_type_concept_id,
  NULL::DATE AS specimen_date,
  NULL::TIMESTAMP AS specimen_datetime,
  NULL::DECIMAL(18, 3) AS quantity,
  NULL::INT AS unit_concept_id,
  NULL::INT AS anatomic_site_concept_id,
  NULL::INT AS disease_status_concept_id,
  NULL::TEXT AS specimen_source_id,
  NULL::TEXT AS specimen_source_value,
  NULL::TEXT AS unit_source_value,
  NULL::TEXT AS anatomic_site_source_value,
  NULL::TEXT AS disease_status_source_value
WHERE
  1 = 0