MODEL (
  name synthea.claims,
  kind SEED (
    path '$root/seeds/synthea/claims.csv'
  ),
  columns (
    Id TEXT,
    PATIENTID TEXT,
    PROVIDERID TEXT,
    PRIMARYPATIENTINSURANCEID TEXT,
    SECONDARYPATIENTINSURANCEID TEXT,
    DEPARTMENTID INT,
    PATIENTDEPARTMENTID INT,
    DIAGNOSIS1 TEXT,
    DIAGNOSIS2 TEXT,
    DIAGNOSIS3 TEXT,
    DIAGNOSIS4 TEXT,
    DIAGNOSIS5 TEXT,
    DIAGNOSIS6 TEXT,
    DIAGNOSIS7 TEXT,
    DIAGNOSIS8 TEXT,
    REFERRINGPROVIDERID TEXT,
    APPOINTMENTID TEXT,
    CURRENTILLNESSDATE TIMESTAMP,
    SERVICEDATE TIMESTAMP,
    SUPERVISINGPROVIDERID TEXT,
    STATUS1 TEXT,
    STATUS2 TEXT,
    STATUSP TEXT,
    OUTSTANDING1 REAL,
    OUTSTANDING2 REAL,
    OUTSTANDINGP REAL,
    LASTBILLEDDATE1 TIMESTAMP,
    LASTBILLEDDATE2 TIMESTAMP,
    LASTBILLEDDATEP TIMESTAMP,
    HEALTHCARECLAIMTYPEID1 INT,
    HEALTHCARECLAIMTYPEID2 INT
  )
)