MODEL (
  name synthea.encounters,
  kind SEED (
    path '$root/seeds/synthea/encounters.csv'
  ),
  columns (
    Id TEXT,
    START TIMESTAMP,
    STOP TIMESTAMP,
    PATIENT TEXT,
    ORGANIZATION TEXT,
    PROVIDER TEXT,
    PAYER TEXT,
    ENCOUNTERCLASS TEXT,
    CODE TEXT,
    DESCRIPTION TEXT,
    BASE_ENCOUNTER_COST REAL,
    TOTAL_CLAIM_COST REAL,
    PAYER_COVERAGE REAL,
    REASONCODE TEXT,
    REASONDESCRIPTION TEXT
  )
)