MODEL (
  name synthea.payers,
  kind SEED (
    path '$root/seeds/synthea/payers.csv'
  ),
  columns (
    Id TEXT,
    NAME TEXT,
    ADDRESS TEXT,
    CITY TEXT,
    STATE_HEADQUARTERED TEXT,
    ZIP INT,
    PHONE TEXT,
    AMOUNT_COVERED REAL,
    AMOUNT_UNCOVERED REAL,
    REVENUE REAL,
    COVERED_ENCOUNTERS INT,
    UNCOVERED_ENCOUNTERS INT,
    COVERED_MEDICATIONS INT,
    UNCOVERED_MEDICATIONS INT,
    COVERED_PROCEDURES INT,
    UNCOVERED_PROCEDURES INT,
    COVERED_IMMUNIZATIONS INT,
    UNCOVERED_IMMUNIZATIONS INT,
    UNIQUE_CUSTOMERS INT,
    QOLS_AVG REAL,
    MEMBER_MONTHS INT
  )
)